---
- hosts: all
  name: Executing pre_tasks
  become: true
  pre_tasks:
###########################################################################
### PRE TASKS
###########################################################################
  - name: Update repo index
    tags:
      - basic
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600
      upgrade: full
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  - name: Reboot if necessary
    ansible.builtin.include_role:
      name: arillso.system.reboot
    vars:
      reboot_post_reboot_delay: 60
  
  # - name: Configure Connection
  #   community.general.nmcli:
  #     conn_name: ens18
  #     ifname: ens18
  #     ip4:
  #       - 10.10.10.80/24
  #     gw4: 10.10.10.1
  #     autoconnect: true
  #     dns4:
  #       - 10.10.10.1
  #     type: ethernet
  #     state: present

  # - name: make sure that ansible requirements are present
  #   tags: always
  #   shell: |
  #     ansible-galaxy install -r ./playbooks/requirements.yml
  #   changed_when: false

###########################################################################
### MAIN TASKS
###########################################################################
- hosts: all
  name: Main |
  roles:
    # - sbaerlocher.qemu-guest-agent # DOCS: https://github.com/sbaerlocher/ansible.qemu-guest-agent

# Oasis_roles documentation: https://github.com/oasis-roles/ansible_collection_system/tree/main/roles
    - role: oasis_roles.system.sudoers
      tags:
        - all
        - basic
        - common
      vars:
        sudoers_groups_no_password: "{{ _sudoers_group_no_password }}"
        sudoers_no_password: "{{ _sudoers_no_password }}"

    - role: common
      tags:
        - all
        - basic
        - common

    - role: common_apps
      tags:
        - all
        - common

    - role: oasis_roles.system.hostname
      tags:
        - all
        - basic
        - common
        - change-hostname
      vars:
        hostname: "{{ _hostname }}"
        hostname_aliases:
          - "{{ _hostname }}"

    - role: gantsign.git_user
      tags:
        - all
        - basic
        - common
        - add-gituser
      become: true
      users:
        - username: clauber
          git_user_name: Clauber Santos
          git_user_email: claubervs@gmail.com
          git_user_force: true

    - role: slick_shell
      tags:
        - all
        - common
        - provision-slick-shell

    - role: chezmoi
      tags:
        - all
        - common
        - provision-chezmoi
    
    - role: brew
      tags:
        - all
        - provision-homebrew

    - role: docker
      tags:
        - all
        - provision-docker


###########################################################################
### POST TASKS
###########################################################################
- hosts: all
  name: Post Tasks | Executing post_tasks
  post_tasks:
    # - name: Post Tasks | Check that the reboot-required exists
    #   ansible.builtin.stat:
    #     path: /var/run/reboot-required
    #   register: p
    # - name: Post Tasks | Debug
    #   ansible.builtin.debug:
    #     msg: "Reboot required"
    #   when: p.stat.exists
    # - name: Post Tasks | Reboot
    #   ansible.builtin.reboot:
        # msg: Rebooting
      # when: p.stat.exists
  - name: Reboot if necessary
    ansible.builtin.include_role:
      name: arillso.system.reboot
    vars:
      reboot_post_reboot_delay: 60

# TODO: Include the upgrade process to update all installed tools to the latest version.
...
