---
# Documentation website
# https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
#
# To install these roles please run the command below:
# ansible-galaxy install -r ./playbooks/requirements.yml
roles:
  - wayofdev.dotfiles
  # - wayofdev.homebrew
  - markosamuli.linuxbrew
  - geerlingguy.git
  - sbaerlocher.qemu-guest-agent
  - gantsign.git_user
  - gantsign.oh-my-zsh
  - ctorgalson.nerdfonts

collections:
  - community.general
  # - scruffaluff.bootware
  - arillso.system
  - oasis_roles.system
...
