---

- hosts: all
  name: Ensuring homebrew is present
  environment:
    - PATH: "{{ homebrew_search_paths | join(':') }}:{{ ansible_env.PATH }}"
  vars:
    - homebrew_repository_use_master: true
    - homebrew_user: linuxbrew  # FYI: can be skipped, as automatically detected, but linuxbrew user is recommended way for installing Homebrew with Linux
    - homebrew_group: linuxbrew  # same as homebrew_user
    - homebrew_upgrade_all: true
    - homebrew_clear_cache: true
    - homebrew_collect_analytics: false
    - homebrew_taps:
        - name: "homebrew/cask-versions"
          state: "present"
        - name: "homebrew/cask-fonts"
          state: "present"
        - name: "jesseduffield/lazygit"
          url: "https://github.com/jesseduffield/lazygit"
          state: "present"
    - homebrew_packages:
      - fzf
      - lazygit
      - navi
      - tldr
      - rsync
      - rclone
      - sops
      - age
      - zellij
  roles:
  - wayofdev.homebrew # DOCS: https://galaxy.ansible.com/wayofdev/homebrew

...
