---
- name: ensuring required software is present
  block:
    - name: ensure required software is present
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
        cache_valid_time: 21600
      when: ansible_distribution == "Ubuntu"
      become: true
      loop: '{{ required_software|flatten(1) }}'

- name: ensuring basic software is present
  block:
    - name: ensure basic software is present
      apt:
        name: '{{ item }}'
        state: present
        cache_valid_time: 21600
      when: ansible_distribution == "Ubuntu"
      become: true
      loop: '{{ basic_software|flatten(1) }}'