---
- name: Main | ensuring required software is present
  tags: basic
  block:
    - name: Main | Ensure required software is present
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: true
        cache_valid_time: 21600
      when: ansible_distribution == "Ubuntu"
      become: true
      loop: '{{ required_software | flatten(1) }}'

- name: Main | Ensuring basic software is present
  tags: basic
  block:
    - name: Main | ensure basic software is present
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        cache_valid_time: 21600
      when: ansible_distribution == "Ubuntu"
      become: true
      loop: '{{ basic_software | flatten(1) }}'
...
