---
- hosts: ubuntu
  name: Playbook | remove need for sudo password
  become: true
  tasks:
    - name: Ensure sudo password is not required
      tags: sudo
    # NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
