---
- name: Chezmoi Main
  tags:
    - basic
    - chezmoi
  block:
    - name: Main | Ensure chezmoi is present in the system
      become: true
      community.general.snap:
        name:
          - chezmoi
        state: present
        classic: true

    - name: Main | Ensure chezmoi repository is present
      # become: true
      register: cz_present
      changed_when: cz_present.rc == 0
      failed_when: cz_present.rc != 0
      ansible.builtin.command:
        cmd: 'chezmoi init --apply {{ _chezmoi_username }}'
        chdir: /home/clauber/

    - name: Main | Ensure chezmoi repository is updated
      # become: true
      register: cz_updated
      changed_when: cz_updated.rc == 0
      failed_when: cz_present.rc != 0
      ansible.builtin.command:
        cmd: 'chezmoi update'
        chdir: /home/clauber/
...
