---

- name: Check if Homebrew is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: b

- name: Install Homebrew # noqa:risky-shell-pipe
  become_user: linuxbrew
  ansible.builtin.shell: |
    yes "\n" | NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not b.stat.exists

- name: Install homebrew taps
  ansible.builtin.homebrew_tap:
    name: "{{ _homebrew_taps }}"
    state: present
  loop: "{{ _homebrew_taps }}"

- name: Install homebrew formulaes
  ansible.builtin.homebrew:
    name: "{{ _homebrew_formulaes }}"
    state: present
  loop: "{{ _homebrew_formulaes }}"

...
