---
- name: Main
  tags:
    - basic
  block:
    - name: Main | bootstrapping
      include_tasks: bootstrap.yml
      # TODO: include a when clause, bootstrapping should run if there is no ssh keypair for the user or no ansible user present.

    - name: Main | make sure ssh key is present in the machine for the user ansible
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWnKkok7MjWFeJ4eCcxhaH9STAk8qiH/9d1q1iyNBRW ansible default"
      become: true

    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: Main | ensure qemu guest agent when on proxmox
      tags: guestagent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
      when: ansible_system_vendor == 'QEMU'

    - name: Main | check if restart is required
      tags: restart
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: p

    - name: Write to debug
      tags: restart
      ansible.builtin.debug:
        msg: "Reboot required"
      when: p.stat.exists

    - name: Main | restart
      tags: restart
      become: true
      ansible.builtin.reboot:
        post_reboot_delay: 60
      when: p.stat.exists

    - name: Main | Gather facts after reboot
      tags: restart
      ansible.builtin.setup:
      when: p.stat.exists
...
