---
- name: Set path to .zshrc
  ansible.builtin.set_fact:
    linuxbrew_zshrc_path: "{{ linuxbrew_home }}/.zshrc"
  when: linuxbrew_zshrc_path is undefined

- name: Check whether .zshrc exists
  ansible.builtin.stat:
    path: "{{ linuxbrew_zshrc_path }}"
  register: linuxbrew_zshrc_st

- name: Resolve .zshrc symlink
  ansible.builtin.set_fact:
    linuxbrew_zshrc_path: "{{ linuxbrew_zshrc_st.stat.lnk_source }}"
  when: linuxbrew_zshrc_st.stat.exists and linuxbrew_zshrc_st.stat.islnk

- name: Load Linuxbrew in .zshrc
  ansible.builtin.blockinfile:
    dest: "{{ linuxbrew_zshrc_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: linuxbrew"
    block: |
      eval $({{ linuxbrew_prefix }}/bin/brew shellenv)
  when: linuxbrew_zshrc_st.stat.exists
