---
username: 'clauber'
user_path: '~'
config_path: '{{ user_path }}'

zshrc_filename: .zshrc
zshrc_fullpath: '{{ config_path }}/{{ zshrc_filename }}'

aliases_filename: .bash_aliases
aliases_fullpath: '{{ config_path }}/{{ aliases_filename }}'

omz_path: '{{ config_path }}/.oh-my-zsh'
omz_plugin_path: '{{ omz_path }}/plugins'
omz_custom_plugin_path: '{{ omz_path }}/custom/plugins'
omz_custom_theme_path: '{{ omz_path }}/custom/themes'

zsh_included_plugins:
  - git

zsh_plugins:
  - name: "zsh-autosuggestions"
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
  - name: "zsh-syntax-highlighting"
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
  - name: "fzf-tab"
    repo: "https://github.com/Aloxaf/fzf-tab"

zsh_themes:
  - name: "powerlevel10k"
    repo: "https://github.com/romkatv/powerlevel10k"

enabled_zsh_theme: "powerlevel10k/powerlevel10k"

zsh_user: clauber

system_user_name: "{{ username }}"
system_user_group: "{{ username }}"
...
