---

- name: Oh-My-ZSH Install Main | Ensure oh-my-zsh
  tags:
    - basic
    - zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ zsh_user }}"
        oh_my_zsh:
          theme: "{{ zsh_theme }}"
          plugins:
            - "{{ zsh_included_plugins }}"
  when: installed.state == "absent"

# - name: Download oh-my-zsh script
#   # become: true
#   ansible.builtin.get_url:
#     url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
#     dest: '{{ user_path }}/ohmyzsh.sh'
#     mode: 0744

# - name: Install oh-my-zsh script
#   # become: true
#   ansible.builtin.command: '{{ user_path }}/ohmyzsh.sh --keep-zshrc -unattended'
#   register: install
#   changed_when: install.rc == 0

# - name: Remove oh-my-zsh install script
#   # become: true
#   ansible.builtin.file:
#     path: '{{ user_path }}/ohmyzsh.sh'
#     state: absent
...
