---

- name: ensure docker is present
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    ansible_become: true
    docker_users: "{{ _docker_users }}"
    docker_install_compose_plugin: true

...
