---
- hosts: ubuntu
  name: Playbook | clear space in Ubuntu
  become: true

  tasks:
    - name: Fix any broken install
      ansible.builtin.shell: |
        sudo apt --fix-broken install

    - name: Remove old kernels
      ansible.builtin.shell: |
        sudo apt autoremove --purge

    - name: Clean apt cache
      ansible.builtin.shell: |
        sudo apt-get clean
