---
- name: Install Docker engine
  hosts: ubuntu

  become: true
  tasks:

  - name: Install depedencies
    apt:
      name: 
       - ca-certificates 
       - curl 
       - gnupg-agent
       - lsb-release
       - software-properties-common
      state: present
      update_cache: true
    become: true

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      filename: docker 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker engine
    apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      state: present
      update_cache: true
    become: true

  - name: test docker
    command: docker info
    become: true