---
- name: Playbook | Install Docker engine
  hosts: ubuntu
  become: true
  tasks:

  - name: Install depedencies
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg-agent
        - lsb-release
        - software-properties-common
      state: present
      update_cache: true
      cache_valid_time: 3600
    become: true

  - name: Add GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repository to apt
    ansible.builtin.apt_repository:
      filename: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker engine
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: true
    become: true

  # - name: Test docker
  #   ansible.builtin.command: docker info
  #   become: true
