---
- name: Ensure python3 and pip3 are present
  hosts: all
  become: true
  tasks:
  - name: Ensure python3 is present
    tags: python
    ansible.builtin.apt:
      name: python3
      state: present
      update_cache: true
  - name: Ensure pip3 is present
    tags: pip, python
    ansible.builtin.apt:
      name: python3-pip
      state: present
      update_cache: true
...
