---
- hosts: all
  name: Making sure software is present and updated in the machine
  become: true
  tasks:
    - name: prequisites
      apt:
        name:
          - curl
        state: present
        update_cache: yes
    - name: Ensure NCDU is present
      apt:
        name: ncdu
        state: present
        cache_valid_time: 3600
    - name: Ensure NALA is present (Ubuntu >= 22)
      apt:
        name: nala
      when:
        - ansible_facts['ansible_distribution'] == "Ubuntu"
        - ansible_facts['ansible_distribution_version'] >= "22"
    - name: Ensure NALA is present (Ubuntu < 22)
      msg: "TBD"
    - name: MICRO
      shell: "curl https://getmic.ro | bash"