---
- name: Ensure python3 and pip3 are present
  hosts: all
  become: yes
  tasks:
  - name: Ensure python3 is present
    apt:
      name: python3
      state: present
      update_cache: yes
  - name: Ensure pip3 is present
    apt:
      name: python3-pip
      state: present
      update_cache: yes
...