---
- hosts: all
  name: make sure required software is present in the machine
  become: true

  pre_tasks:
    - name: make sure required software is installed is installed
      apt:
        name:
          - curl
        state: present
        update_cache: yes
        cache_valid_time: 3600


  tasks:
    - name: Ensure NCDU is present (Ubuntu)
      apt:
        name: ncdu
        state: present
        cache_valid_time: 3600
      when: ansible_distribution == "Ubuntu"
        
    - name: Ensure NALA is present (Ubuntu >= 22)
      apt:
        name: nala
        state: present
      when:
        - ansible_facts['distribution_major_version'] is version('22', '>=')
    # - name: Ensure NALA is present (Ubuntu < 22)
      # msg: "TBD"

    - name: Ensure MICRO is present (Ubuntu)
      apt:
        name: micro
        state: present
      when: ansible_distribution == "Ubuntu"

    # - name: Make sure MICRO is present and universal
    #   stat:
    #     path: "/usr/bin/micro"
    #   register: microtest
    
    # - name: Install MICRO
    #   shell: |
    #     "cd /usr/bin"
    #     "sudo curl https://getmic.ro | bash"
    #   when: microtest.stat.exists is not defined