---
- hosts: all
  name: Playbook | qemu guest agent
  tasks:
    - name: Ensure qemu-guest-agent is present
      tags: guestagent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
