---
- hosts: all
  tasks:
    - name: Ensure qemu-guest-agent is present
      tags: guestagent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
      become: true