---
- hosts: all
  become: true
  pre_tasks:


  - name: update repo index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      cache_valid_time: 3600
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  # - name: make sure that ansible requirements are present
  #   tags: always
  #   shell: |
  #     ansible-galaxy install -r ./playbooks/requirements.yml
  #   changed_when: false


- hosts: all
  # become: true
  roles:
    - base
    - base_apps
    # - slick_shell
    # - chezmoi


# - hosts: all
#   post_tasks:
  # TODO: Include the upgrade process to update all installed tools to the latest version.