---
- hosts: all
  become: true
  pre_tasks:


  - name: update repo index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      cache_valid_time: 3600
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  # - name: make sure that ansible requirements are present
  #   tags: always
  #   shell: |
  #     ansible-galaxy install -r ./playbooks/requirements.yml
  #   changed_when: false


- hosts: all
  # become: true
  roles:
    # - sbaerlocher.qemu-guest-agent # DOCS: https://github.com/sbaerlocher/ansible.qemu-guest-agent
    # - base
    # - base_apps
    # - role: wayofdev.dotfiles
    #   environment:
    #     - PATH: "/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
    #   vars:
    #     - dotfiles_repository_url: "https://github.com/claubervs/ansible.git"
    #     - dotfiles_repository_branch: main
    - role: wayofdev.homebrew # DOCS: https://galaxy.ansible.com/wayofdev/homebrew
      become: true
      environment:
        - PATH: "{{ homebrew_search_paths | join(':') }}:{{ ansible_env.PATH }}"
      vars:
        # - homebrew_user: linuxbrew  # FYI: can be skipped, as automatically detected, but linuxbrew user is recommended way for installing Homebrew with Linux
        # - homebrew_group: linuxbrew  # same as homebrew_user
        - homebrew_upgrade_all: true
        - homebrew_clear_cache: true
        - homebrew_collect_analytics: false
        - homebrew_taps:
          - name: homebrew/core
            state: present
          - name: homebrew/cask-versions
            state: present
          - name: homebrew/cask-fonts
            state: present
          - name: jesseduffield/lazygit/lazygit
            state: present
        - homebrew_packages:
          - fzf
          - lazygit
          - navi
          # - rsync
          # - rclone
          # - sops
          - tldr
          # - age
          # - zellij
    # - slick_shell
    # - chezmoi


- hosts: all
  post_tasks:
    - name: Check that the reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: p
    - debug:
        msg: "Reboot required"
      when: p.stat.exists == true
    - name: Reboot
      reboot:
        msg: Rebooting
      when: p.stat.exists == true

# TODO: Include the upgrade process to update all installed tools to the latest version.