---
- hosts: all
  
  become: true

  tasks:
    - name: Ensuring all installed packages are up to date
    tags: all
      apt:
        name: "*"
        update_cache: yes
        cache_valid_time: 3600
        state: latest