---
# Shared directory to install Linuxbrew in
linuxbrew_prefix_shared: "/home/linuxbrew/.linuxbrew"

# Brew Git repository
linuxbrew_brew_repo: https://github.com/Homebrew/brew
linuxbrew_brew_version: master
linuxbrew_core_tap_repo: https://github.com/Homebrew/linuxbrew-core
linuxbrew_core_tap_version: master

# Linuxbrew installer script
linuxbrew_install_tmp: "/tmp/linuxbrew"
linuxbrew_install_url: "https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
linuxbrew_install_checksum: "sha256:45c12bcd7765986674142230fc0860f5274903adbe37d582e5537771a1bae0b8"

linuxbrew_install_dependencies:
  - git
  - curl
  - build-essential
  - locales
  - language-pack-en
