- name: ensure zsh is present
  apt:
    name: zsh
    state: present
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu"

- name: ensure zsh as default shell
  shell: |
    chsh -s $(which zsh)
  # change_when: false

- name: download oh-my-zsh
  get_url:
    url:
      https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/ohmyzsh.sh
    mode: 0744

- name: install oh-my-zsh
  command: ~/ohmyzsh.sh --keep-zshrc
  register: install
  changed_when: install.rc == 0

- name: remove instakller script
  file:
    path: ~/ohmyzsh.sh
    state: absent


# - name: ensure powerlevel10k is present


# - name: ensure personal .bash_aliases is present



# - name: ensure personal .zshrc is present


# - name: ensure personal .p10k.zsh is present
