- name: ensure zsh is present
  apt:
    name: zsh
    state: present
    cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu"

- name: ensure zsh as default shell
  shell: |
    chsh -s $(which zsh)
  register: ret
  changed_when: ret.rc != 0

- name: check oh-my-zsh is present
  file:
    state: file
    path: ~/.oh-my-zsh/oh-my-zsh.sh
  register: installed
  failed_when: false
  # changed_when: installed.state == "absent"

- name: install oh-my-zsh
  include_tasks: oh-my-zsh-install.yml
  when: installed.state == "absent"


# - name: ensure powerlevel10k is present


# - name: ensure personal .bash_aliases is present



# - name: ensure personal .zshrc is present


# - name: ensure personal .p10k.zsh is present
